# Generated by Django 3.2.3 on 2021-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_answer_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='title',
            new_name='ans1',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='lock_other',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
        migrations.AddField(
            model_name='choice',
            name='ans2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='ans3',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='key',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.TextField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
