# Generated by Django 3.2.3 on 2021-06-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210609_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'permissions': (('can_post', 'Can add post'), ('can_manage_post', 'Can manage post'))},
        ),
    ]
