# Generated by Django 3.2.3 on 2021-06-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_choice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'permissions': (('can_add_choise', 'Can add choise'), ('can_delete_choise', 'Can delete cgoise'))},
        ),
    ]
