# Generated by Django 3.2.3 on 2021-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_choice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'permissions': (('can_add_choice', 'Can add choice'), ('can_delete_choice', 'Can delete choice'))},
        ),
        migrations.AlterField(
            model_name='choice',
            name='ans1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='ans2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='ans3',
            field=models.CharField(max_length=100),
        ),
    ]
