# Generated by Django 3.2.3 on 2021-06-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210610_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
