# Generated by Django 3.2.3 on 2021-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210610_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='key',
            field=models.IntegerField(default=1),
        ),
    ]
